#!/usr/bin/env python3
"""
build_pack.py - pack the XRPBlocks IDE into one encrypted file (xrpblocks.pak)
that only XRPServePack.exe can open.

Usage (run from the XRPBlocks folder):
    python tools/build_pack.py --genkey      # once: create delphiSource/PackKey.inc
    python tools/build_pack.py               # build packtest/xrpblocks.pak
    python tools/build_pack.py --verify      # decrypt the pack and compare with disk

The key lives in delphiSource/PackKey.inc. XRPServePack.dpr compiles it in,
and this script reads the same file, so the two always match. Rebuild the
exe after --genkey; rebuild only the pack after an IDE change.

File format (all integers little-endian):
    "XRPK"  (4 bytes)   magic
    0x01    (1 byte)    format version
    nonce   (16 bytes)  random per build
    body    (n bytes)   encrypted payload
    tag     (32 bytes)  HMAC-SHA256(macKey, magic+version+nonce+body)

    encKey = SHA256(key + b"enc"),  macKey = SHA256(key + b"mac")
    keystream block i = SHA256(encKey + nonce + uint64(i)), body = payload XOR keystream

    payload = uint32 count, then per file:
              uint16 pathLen, path (UTF-8, lower case, "/" separators),
              uint32 dataLen, data
"""
import argparse, hashlib, hmac, os, re, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY_INC = os.path.join(ROOT, 'delphiSource', 'PackKey.inc')
DEFAULT_OUT = os.path.join(ROOT, 'packtest', 'xrpblocks.pak')

# What the running IDE actually loads. Everything else (tools, docs, Delphi
# source, Python drivers, backups) stays out of the pack.
INCLUDE_FILES = ['index.html', 'LICENCES.txt']
INCLUDE_DIRS = ['css', 'js', 'devices', 'images', 'lessons', 'examples']
EXCLUDE_EXT = {'.py', '.pyc', '.md', '.pdf'}
EXCLUDE_NAME_PARTS = ['.bak']

MAGIC = b'XRPK'
VERSION = 1


def read_key():
    if not os.path.exists(KEY_INC):
        sys.exit('No key yet: run  python tools/build_pack.py --genkey  first.')
    with open(KEY_INC, encoding='utf-8') as f:
        text = f.read()
    body = text.split('(', 1)[1] if '(' in text else ''
    key = bytes(int(h, 16) for h in re.findall(r'\$([0-9A-Fa-f]{2})', body))
    if len(key) != 32:
        sys.exit(f'PackKey.inc should hold 32 bytes, found {len(key)}.')
    return key


def gen_key():
    if os.path.exists(KEY_INC):
        sys.exit('PackKey.inc already exists. Delete it yourself first if you '
                 'really want a new key (old packs will stop opening).')
    key = os.urandom(32)
    rows = []
    for i in range(0, 32, 8):
        rows.append('    ' + ', '.join(f'${b:02X}' for b in key[i:i + 8]))
    inc = ('// Generated by tools/build_pack.py --genkey. Keep this file private.\n'
           '// It must match the key used to build xrpblocks.pak.\n'
           'const\n'
           '  PACK_KEY: array[0..31] of Byte = (\n'
           + ',\n'.join(rows) + ');\n')
    with open(KEY_INC, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write(inc)
    print('Wrote', KEY_INC)


def collect():
    files = []
    for name in INCLUDE_FILES:
        files.append(name)
    for d in INCLUDE_DIRS:
        base = os.path.join(ROOT, d)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [x for x in dirnames if x != '__pycache__']
            for fn in filenames:
                if os.path.splitext(fn)[1].lower() in EXCLUDE_EXT:
                    continue
                if any(p in fn for p in EXCLUDE_NAME_PARTS):
                    continue
                rel = os.path.relpath(os.path.join(dirpath, fn), ROOT)
                files.append(rel.replace(os.sep, '/'))
    return sorted(set(files))


def keystream_xor(enc_key, nonce, data):
    out = bytearray(len(data))
    for i in range(0, len(data), 32):
        ks = hashlib.sha256(enc_key + nonce + struct.pack('<Q', i // 32)).digest()
        chunk = data[i:i + 32]
        out[i:i + len(chunk)] = bytes(a ^ b for a, b in zip(chunk, ks))
    return bytes(out)


def derive(key):
    return hashlib.sha256(key + b'enc').digest(), hashlib.sha256(key + b'mac').digest()


def build(out_path):
    key = read_key()
    enc_key, mac_key = derive(key)
    files = collect()
    lowered = [f.lower() for f in files]
    if len(set(lowered)) != len(lowered):
        sys.exit('Two files differ only by upper/lower case; rename one.')
    parts = [struct.pack('<I', len(files))]
    total = 0
    for rel in files:
        with open(os.path.join(ROOT, rel), 'rb') as f:
            data = f.read()
        p = rel.lower().encode('utf-8')
        parts += [struct.pack('<H', len(p)), p, struct.pack('<I', len(data)), data]
        total += len(data)
    payload = b''.join(parts)
    nonce = os.urandom(16)
    header = MAGIC + bytes([VERSION]) + nonce
    body = keystream_xor(enc_key, nonce, payload)
    tag = hmac.new(mac_key, header + body, hashlib.sha256).digest()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'wb') as f:
        f.write(header + body + tag)
    print(f'Packed {len(files)} files ({total:,} bytes) into {out_path}')


def unpack(path, key):
    enc_key, mac_key = derive(key)
    with open(path, 'rb') as f:
        blob = f.read()
    if len(blob) < 21 + 32 or blob[:4] != MAGIC or blob[4] != VERSION:
        raise ValueError('not an XRPK v1 pack')
    header, body, tag = blob[:21], blob[21:-32], blob[-32:]
    if not hmac.compare_digest(tag, hmac.new(mac_key, header + body, hashlib.sha256).digest()):
        raise ValueError('pack is damaged or has been modified')
    payload = keystream_xor(enc_key, header[5:21], body)
    (count,) = struct.unpack_from('<I', payload, 0)
    pos, entries = 4, {}
    for _ in range(count):
        (pl,) = struct.unpack_from('<H', payload, pos); pos += 2
        p = payload[pos:pos + pl].decode('utf-8'); pos += pl
        (dl,) = struct.unpack_from('<I', payload, pos); pos += 4
        entries[p] = payload[pos:pos + dl]; pos += dl
    if pos != len(payload):
        raise ValueError('payload length mismatch')
    return entries


def verify(path):
    entries = unpack(path, read_key())
    bad = 0
    for rel in collect():
        with open(os.path.join(ROOT, rel), 'rb') as f:
            if entries.get(rel.lower()) != f.read():
                print('MISMATCH', rel); bad += 1
    print(f'{len(entries)} files in pack, {bad} mismatches')
    return bad == 0


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--genkey', action='store_true')
    ap.add_argument('--verify', action='store_true')
    ap.add_argument('--out', default=DEFAULT_OUT)
    a = ap.parse_args()
    if a.genkey:
        gen_key()
    elif a.verify:
        sys.exit(0 if verify(a.out) else 1)
    else:
        build(a.out)
